/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    BackToTop: typeof import("./src/components/shared/BackToTop.vue")["default"]
    Breadcrumb: typeof import("./src/components/shared/Breadcrumb.vue")["default"]
    BuyNow: typeof import("./src/components/BuyNow.vue")["default"]
    CardStatisticsVertical: typeof import("./src/components/CardStatisticsVertical.vue")["default"]
    CarouselImage: typeof import("./src/components/table/CarouselImage.vue")["default"]
    CopyLabel: typeof import("./src/components/common/CopyLabel.vue")["default"]
    CountDown: typeof import("./src/components/shared/CountDown.vue")["default"]
    DataFilter: typeof import("./src/components/table/DataFilter.vue")["default"]
    DatePicker: typeof import("./src/components/shared/DatePicker.vue")["default"]
    DelayButton: typeof import("./src/components/shared/DelayButton.vue")["default"]
    DragSorted: typeof import("./src/components/shared/DragSorted.vue")["default"]
    Dropzone: typeof import("./src/components/shared/Dropzone.vue")["default"]
    Editor: typeof import("./src/components/editor/TuiEditor/Editor.vue")["default"]
    EditorMd: typeof import("./src/components/editor/EditorMd.vue")["default"]
    FileImageUpload: typeof import("./src/components/shared/FileImageUpload.vue")["default"]
    FileMultipleImageInput: typeof import("./src/components/shared/FileMultipleImageInput.vue")["default"]
    FileSingleImageInput: typeof import("./src/components/shared/FileSingleImageInput.vue")["default"]
    FileUpload: typeof import("./src/components/FileUpload.vue")["default"]
    FlagIcon: typeof import("./src/components/common/FlagIcon.vue")["default"]
    ImageRemove: typeof import("./src/components/shared/ImageRemove.vue")["default"]
    ImageWithDelete: typeof import("./src/components/table/ImageWithDelete.vue")["default"]
    Index_3: typeof import("./src/components/myEditor/index_3.vue")["default"]
    InputInteger: typeof import("./src/components/shared/InputInteger.vue")["default"]
    InputNumber: typeof import("./src/components/shared/InputNumber.vue")["default"]
    Loading: typeof import("./src/components/shared/Loading.vue")["default"]
    MainMenu: typeof import("./src/components/navigation/MainMenu.vue")["default"]
    MyEditor: typeof import("./src/components/myEditor/index.vue")["default"]
    NavMenu: typeof import("./src/components/navigation/NavMenu.vue")["default"]
    NavMenuItem: typeof import("./src/components/navigation/NavMenuItem.vue")["default"]
    NumberFiler: typeof import("./src/components/table/filter/NumberFiler.vue")["default"]
    OneTimePwd: typeof import("./src/components/OneTimePwd.vue")["default"]
    PaginationRow: typeof import("./src/components/shared/PaginationRow.vue")["default"]
    ReloadButton: typeof import("./src/components/ReloadButton.vue")["default"]
    RouterLink: typeof import("vue-router")["RouterLink"]
    RouterView: typeof import("vue-router")["RouterView"]
    SideConfigMenu: typeof import("./src/components/common/SideConfigMenu.vue")["default"]
    SvgIcon: typeof import("./src/components/common/SvgIcon.vue")["default"]
    TableImage: typeof import("./src/components/table/TableImage.vue")["default"]
    TextTooltip: typeof import("./src/components/table/TextTooltip.vue")["default"]
    ThirdDropzone: typeof import("./src/components/shared/ThirdDropzone.vue")["default"]
    TrendPercent: typeof import("./src/components/common/TrendPercent.vue")["default"]
    Viewer: typeof import("./src/components/editor/TuiEditor/Viewer.vue")["default"]
    VToast: typeof import("./src/components/VToast.vue")["default"]
    VuetifyProvider: typeof import("./src/components/provider/VuetifyProvider.vue")["default"]
  }
}
