/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/application/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/application/AppHeader.vue')['default']
    BackToTop: typeof import('./src/components/shared/BackToTop.vue')['default']
    Breadcrumb: typeof import('./src/components/shared/Breadcrumb.vue')['default']
    CarouselImage: typeof import('./src/components/table/CarouselImage.vue')['default']
    CountDown: typeof import('./src/components/shared/CountDown.vue')['default']
    DatePicker: typeof import('./src/components/shared/DatePicker.vue')['default']
    DelayButton: typeof import('./src/components/shared/DelayButton.vue')['default']
    DragSorted: typeof import('./src/components/shared/DragSorted.vue')['default']
    Dropzone: typeof import('./src/components/shared/Dropzone.vue')['default']
    FileMultipleImageInput: typeof import('./src/components/shared/FileMultipleImageInput.vue')['default']
    FileSingleImageInput: typeof import('./src/components/shared/FileSingleImageInput.vue')['default']
    FileUpload: typeof import('./src/components/shared/FileUpload.vue')['default']
    ImageRemove: typeof import('./src/components/shared/ImageRemove.vue')['default']
    ImageWithDelete: typeof import('./src/components/table/ImageWithDelete.vue')['default']
    Index_3: typeof import('./src/components/myEditor/index_3.vue')['default']
    InputInteger: typeof import('./src/components/shared/InputInteger.vue')['default']
    Loading: typeof import('./src/components/shared/Loading.vue')['default']
    MyEditor: typeof import('./src/components/myEditor/index.vue')['default']
    PaginationRow: typeof import('./src/components/shared/PaginationRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableImage: typeof import('./src/components/table/TableImage.vue')['default']
    TextTooltip: typeof import('./src/components/table/TextTooltip.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    ThirdDropzone: typeof import('./src/components/shared/ThirdDropzone.vue')['default']
    UserProfile: typeof import('./src/components/application/UserProfile.vue')['default']
  }
}
