version: "3.5"
networks:
  frontend:
    driver: bridge
services:
  nginx:
    build:
      context: ./nginx
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - VERSION=${VERSION}
    volumes:
      - ./log/nginx:/var/log/nginx
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    restart: always
    networks:
      - frontend
