export * from "./crypto"
export * from "./regex"
export * from "./storage"
export * from "./string"
export * from "./toast"
export * from "./typeof"
export * from "./updates"
export * from "./urls"
export * from "./util"
export * from "./validation"
export * from "./validators"
export * from "./collection"
export * from "./common"
export * from "./api.js"
export * from "./nporgress"
export * from "./config"

import i18n from "@/plugins/i18n"
export const t = i18n.global.t
