#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn format
#yarn lint-fix
#git add .
#prettier --write --ignore-unknown "src/**/*.js" "src/**/*.vue"
#eslint "src/**/*.{js,vue}" --fix  --color --cache --max-warnings=-1
#git add .